services:
  - type: web
    name: benchmark-app
    runtime: python
    pythonVersion: "3.11.4"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
